name: Build/release

on:
  push:
    paths:
      - 'apps/software/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 21
      
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Workspace's dependencies
        run: pnpm install
        
      - name: Install Software dependencies
        run: pnpm install --ignore-workspace
        working-directory: apps/software

      - name: Build Files
        run: npm run build
        working-directory: apps/software

      - name: Create Release Binaries
        run: npm run make
        working-directory: apps/software

      - name: Get latest commit message
        run: |
          latest_commit_message=$(git log -1 --pretty=%B)
          echo "commit_message=$latest_commit_message" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: main
          release_name: ${{ env.commit_message }}
          draft: false
          prerelease: false
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./apps/software/out/make/squirrel.windows/x64/CTC-IMS.exe
          asset_name: CTC-IMS.exe
          asset_content_type: application/exe